// Where the game's assets actually live.
//
// The generated models are not in this repository. They are on the studio
// shelf, props.pajama.studio, under content-addressed keys — a URL names exact
// bytes, so the year-long immutable cache in front of them is correct and a
// changed model is a changed URL. No cache-busting query strings, no version
// segments, no purge step when something is re-exported.
//
// src/asset-urls.json is the path -> URL table, regenerated by
// `npm run assets:sync` and committed, so the build stays offline and an asset
// change shows up in review as a changed hash.
import manifest from "./asset-urls.json";

/** What this repository still serves itself, and the reason each one stays.
 *  A trailing slash matches a whole directory. */
const LOCAL = [
  // Procedurally generated here by scripts/, and small. The shelf catalogues
  // models, not the texture set a shader assembles at runtime.
  "textures/",
  // KayKit's CC0 skeleton, third-party. Redistributing someone else's work from
  // a shelf that says "studio-internal" is how attribution gets lost, so it
  // stays here beside the credit in LICENSES.md.
  "skeleton.glb",
  "skeleton-game.glb",
  // Embedded geometry rather than a model file — nothing for the shelf to hold.
  "abyss/cemetery/dead-tree-lods.json",
];

const urls = manifest as Record<string, string>;

const isLocal = (path: string) =>
  LOCAL.some((entry) => (entry.endsWith("/") ? path.startsWith(entry) : path === entry));

/** Set VITE_ASSETS_LOCAL=1 to load everything from public/assets instead —
 *  pair it with `npm run assets:pull` to work with no network. */
const FORCE_LOCAL = import.meta.env?.VITE_ASSETS_LOCAL === "1";

/**
 * Resolve a repo-relative asset path to the URL to fetch it from.
 *
 * Unknown paths throw rather than falling back to /assets/, because that
 * fallback is a 404 in production wearing the costume of a working code path:
 * the file is not in this repository any more. A tier that gets licensed on the
 * shelf, or a model renamed without re-syncing, fails here at startup with the
 * path in hand instead of as a missing mesh someone notices a week later.
 */
export function assetUrl(path: string): string {
  if (FORCE_LOCAL || isLocal(path)) return `/assets/${path}`;
  const url = urls[path];
  if (url) return url;
  throw new Error(
    `asset "${path}" is not in src/asset-urls.json and is not served locally. ` +
      `Add it to a props catalogue and run "npm run assets:sync", or list it in LOCAL in src/assets.ts.`,
  );
}
